# Generated by Django 5.2.3 on 2025-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('president', 'Président'), ('treasurer', 'Trésorier'), ('secrecom', 'Sécrécom'), ('censeur', 'Censeur'), ('accountant', 'Comptable'), ('member', 'Membre'), ('guest', 'Invité'), ('admin', 'Administrateur')], default='guest', max_length=20),
        ),
    ]
