# Generated by Django 5.2.3 on 2025-08-09 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_code_generated_at_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('president', 'Président'), ('treasurer', 'Trésorier'), ('secrecom', 'Sécrécom'), ('censeur', 'Censeur'), ('accountant', 'Comptable'), ('member', 'Membre'), ('guest', 'Invité')], default='guest', max_length=20),
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Avertissement', 'Avertissement'), ('Amende', 'Amende'), ('Exclusion', 'Exclusion')], max_length=20)),
                ('reason', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Vote en cours', 'Vote en cours'), ('Appliquée', 'Appliquée'), ('Rejetée', 'Rejetée')], default='Vote en cours', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='api.member')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_sanctions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanctionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'Pour'), ('against', 'Contre')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sanction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.sanction')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sanction', 'voter')},
            },
        ),
    ]
