# Generated by Django 5.2.3 on 2025-08-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role_sanction_sanctionvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('Ouverture', 'Ouverture du mois'), ('Clôture', 'Clôture du mois'), ('Extraordinaire', 'Extraordinaire'), ('Comité', 'Comité de Gestion')], default='Comité', max_length=20)),
                ('status', models.CharField(choices=[('À venir', 'À venir'), ('En cours', 'En cours'), ('Passée', 'Passée')], default='À venir', max_length=20)),
                ('decisions', models.TextField(blank=True, help_text='Décisions clés prises durant la réunion.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Modification Charte', 'Modification Charte'), ('Sanction', 'Sanction'), ('Prêt Important', 'Prêt Important'), ('Règle', 'Règle')], max_length=50)),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], default='En cours', max_length=20)),
                ('required_majority', models.CharField(choices=[('Simple', 'Simple'), ('Qualifiée', 'Qualifiée'), ('Unanimité', 'Unanimité')], default='Simple', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for', 'Pour'), ('against', 'Contre')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vote_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.vote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vote_proposal', 'voter')},
            },
        ),
    ]
