# Fichier de configuration pour Netlify

[build]
  # Commande à exécuter pour construire le site
  command = "CI=false npm run build"

  # CORRECTION ICI: On enlève "frontend/" car on est déjà dedans grâce à "base"
  publish = "build"

  # Dossier de base pour le build
  base = "frontend"