# Fichier de configuration pour Netlify

[build]
  # Commande à exécuter pour construire le site
  command = "CI=false npm run build"

  # Dossier à publier après le build
  publish = "build"

  # Dossier de base pour le build
  base = "frontend"
  
# Règle de redirection pour les applications à page unique (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
